# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

kafka:
  replicas: 1
  listeners:
    plain: {}
    tls: {}
  config:
    offsets.topic.replication.factor: 1
    auto.create.topics.enable: "true"
    inter.broker.listener.name: plain
    listener.security.protocol.map: plain:PLAINTEXT
    auto.create.topics.enable: "false"
    offsets.topic.replication.factor: 1
    transaction.state.log.replication.factor: 1
    transaction.state.log.min.isr: 1
    default.replication.factor: 1
    min.insync.replicas: 1
  resources:
    requests:
      memory: 2Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: "1"
  loadBalancer:
    ports:
    - name: "broker"
      port: 9092
      targetPort: 9094
  storage:
    type: jbod
    size: 1Gi
    deleteClaim: true
    class: standard
entityOperator:
  topicOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: "0.2"
        limits:
          memory: 256Mi
          cpu: "0.5"
  userOperator:
    resources:
      requests:
        memory: 512Mi
        cpu: "0.2"
      limits:
        memory: 512Mi
        cpu: "0.5"
zookeeper:
  replicas: 1
  resources:
    requests:
      memory: 1Gi
      cpu: "0.3"
    limits:
      memory: 1Gi
      cpu: "0.5"
  storage:
    type: jbod
    size: 1Gi
    deleteClaim: true
    class: standard
