apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  cruiseControl:
    image: n0bis/strimzi-cruise-ui:latest
    config:
      webserver.security.enable: false
  kafka:
    template:
      pod:
        metadata:
          labels:
            broker: "true"
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: broker
                      operator: In
                      values:
                        - "true"
                topologyKey: "kubernetes.io/hostname"
    replicas: 3
    listeners:
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      auto.create.topics.enable: true
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 1
      default.replication.factor: 3
      min.insync.replicas: 1
      log.retention.hours: 168
      log.segment.bytes: 1073741824
      log.retention.check.interval.ms: 300000
      num.network.threads: 3
      num.io.threads: 8
      socket.send.buffer.bytes: 102400
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600
      group.initial.rebalance.delay.ms: 0
      zookeeper.connection.timeout.ms: 6000
    jvmOptions:
      "-Xmx": 8192m
      "-Xms": 8192m
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
      class: premium-rwo 
  entityOperator:
    topicOperator:
        resources:
          requests:
            memory: 256Mi
            cpu: "3"
          limits:
            memory: 256Mi
            cpu: "4"
    userOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "3"
        limits:
          memory: 512Mi
          cpu: "4"
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
      class: premium-rwo 